version: 2
updates:
  - package-ecosystem: docker
    directory: /.github/actions/people
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/graphdb
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /docs/api_reference
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /libs/cli/langchain_cli/project_template
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /libs/community/tests/integration_tests/graphs/docker-compose-ontotext-graphdb
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /libs/langchain
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /libs/langchain/tests/integration_tests/chains/docker-compose-ontotext-graphdb
    schedule:
      interval: daily
