name: Check Broken Links

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * *'

permissions:
  contents: read

jobs:
  check-links:
    if: github.repository_owner == 'langchain-ai'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Use Node.js 18.x
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 18.x
          cache: "yarn"
          cache-dependency-path: ./docs/yarn.lock
      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build
        working-directory: ./docs
      - name: Check broken links
        run: yarn check-broken-links
        working-directory: ./docs
