---
name: CI / cd . / make spell_check

on:
  push:
    branches: [master, v0.1]
  pull_request:
    branches: [master, v0.1]

permissions:
  contents: read

jobs:
  codespell:
    name: (Check for spelling errors)
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Dependencies
        run: |
          pip install toml

      - name: Extract Ignore Words List
        run: |
          # Use a Python script to extract the ignore words list from pyproject.toml
          python .github/workflows/extract_ignored_words_list.py
        id: extract_ignore_words

#      - name: Codespell
#        uses: codespell-project/actions-codespell@v2
#        with:
#          skip: guide_imports.json,*.ambr,./cookbook/data/imdb_top_1000.csv,*.lock
#          ignore_words_list: ${{ steps.extract_ignore_words.outputs.ignore_words_list }}
#          exclude_file: ./.github/workflows/codespell-exclude
